# Generated by Django 4.1.4 on 2023-01-04 17:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_date", models.DateTimeField(default=datetime.datetime.now)),
                ("c_note_number", models.BigIntegerField(unique=True)),
                ("sender_mobile", models.BigIntegerField()),
                (
                    "receiver_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("receiver_mobile_number", models.BigIntegerField()),
                ("ref_courier_number", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=100)),
                (
                    "mobile_number",
                    models.CharField(blank=True, default=9529486594, max_length=15),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="ParcelStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="RefCourier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("link", models.CharField(max_length=1000)),
                (
                    "type",
                    models.CharField(
                        choices=[("External", "External"), ("Internal", "Internal")],
                        default="External",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trackinghistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "in_out_datetime",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("last_updated_datetime", models.DateTimeField(auto_now=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "c_note_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.booking"
                    ),
                ),
                (
                    "d_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_in",
                        to="api.destination",
                    ),
                ),
                (
                    "d_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_out",
                        to="api.destination",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="api.parcelstatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BranchNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=256)),
                ("branch_incharge_number", models.BigIntegerField()),
                ("office_number", models.BigIntegerField(blank=True, null=True)),
                (
                    "office_lane_line_number",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("address", models.TextField()),
                ("pincode", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Franchise", "Franchise"), ("R O", "R O")],
                        max_length=256,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.destination",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="from_destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_destination",
                to="api.destination",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="ref_courier_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.refcourier"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="to_destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_destination",
                to="api.destination",
            ),
        ),
    ]
