# Generated by Django 4.1.4 on 2022-12-25 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="RefCourier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("link", models.CharField(max_length=1000)),
                (
                    "type",
                    models.CharField(
                        choices=[("External", "External"), ("Internal", "Internal")],
                        default="External",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_date", models.DateTimeField(default=datetime.datetime.now)),
                ("c_note_number", models.BigIntegerField()),
                ("sender_mobile", models.BigIntegerField()),
                (
                    "receiver_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("receiver_mobile_number", models.BigIntegerField()),
                ("ref_courier_number", models.CharField(max_length=50)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.destination",
                    ),
                ),
                (
                    "ref_courier_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.refcourier"
                    ),
                ),
            ],
        ),
    ]
