# Generated by Django 4.1.4 on 2022-12-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="ref_courier_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
