# Generated by Django 4.1.4 on 2023-01-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_contactus_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchnetwork",
            name="email",
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
