# Generated by Django 4.1.4 on 2022-12-25 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_parcelstatus_booking_created_at_booking_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackinghistory",
            name="in_out_datetime",
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
