# Generated by Django 4.1.4 on 2023-01-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchnetwork",
            name="office_lane_line_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
