# Generated by Django 4.1.4 on 2022-12-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_trackinghistory_in_out_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trackinghistory", old_name="destination_in", new_name="d_from",
        ),
        migrations.RenameField(
            model_name="trackinghistory", old_name="destination_out", new_name="d_to",
        ),
    ]
