# Generated by Django 4.1.4 on 2022-12-31 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_destination_in_trackinghistory_d_from_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="destination",),
        migrations.AddField(
            model_name="booking",
            name="from_destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_destination",
                to="api.destination",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="to_destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_destination",
                to="api.destination",
            ),
        ),
    ]
