# Generated by Django 4.1.4 on 2022-12-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_booking_destination_booking_from_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackinghistory",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
