# Generated by Django 4.1.4 on 2023-01-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_country_booking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchnetwork",
            name="country",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.country"
            ),
        ),
    ]
