# Generated by Django 4.1.4 on 2023-01-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_branchnetwork_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="sender_name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
