# Generated by Django 4.1.4 on 2023-01-01 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_trackinghistory_in_out_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=256)),
                ("mobile_number", models.BigIntegerField()),
                ("address", models.TextField()),
                ("pincode", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Franchise", "Franchise"), ("R O", "R O")],
                        max_length=256,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.destination",
                    ),
                ),
            ],
        ),
    ]
