# Generated by Django 4.1.4 on 2023-01-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_branchnetwork"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branchnetwork",
            old_name="mobile_number",
            new_name="branch_incharge_number",
        ),
        migrations.AddField(
            model_name="branchnetwork",
            name="office_lane_line_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="branchnetwork",
            name="office_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
