# Generated by Django 4.1.4 on 2023-01-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0011_rename_mobile_number_branchnetwork_branch_incharge_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=12)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
