# Generated by Django 4.1.4 on 2023-01-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_partyaccounts_booking_party_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking", options={"verbose_name_plural": "Booking"},
        ),
        migrations.AlterModelOptions(
            name="branchnetwork",
            options={"verbose_name_plural": "Branch network master"},
        ),
        migrations.AlterModelOptions(
            name="contactus", options={"verbose_name_plural": "Contact us"},
        ),
        migrations.AlterModelOptions(
            name="country", options={"verbose_name_plural": "Country"},
        ),
        migrations.AlterModelOptions(
            name="destination", options={"verbose_name_plural": "Destination"},
        ),
        migrations.AlterModelOptions(
            name="parcelstatus", options={"verbose_name_plural": "Parcel status"},
        ),
        migrations.AlterModelOptions(
            name="partyaccounts", options={"verbose_name_plural": "Party master"},
        ),
        migrations.AlterModelOptions(
            name="refcourier", options={"verbose_name_plural": "Ref. couriers"},
        ),
        migrations.AlterModelOptions(
            name="state", options={"verbose_name_plural": "State"},
        ),
        migrations.AlterModelOptions(
            name="token", options={"verbose_name_plural": "Token"},
        ),
        migrations.AlterModelOptions(
            name="trackinghistory", options={"verbose_name_plural": "Tracking history"},
        ),
        migrations.AlterField(
            model_name="booking",
            name="sender_mobile",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
