# Generated by Django 4.1.4 on 2023-01-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_contactus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
