# Generated by Django 4.1.4 on 2023-01-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_booking_options_alter_branchnetwork_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="receiver_mobile_number",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="sender_mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
