# Generated by Django 4.1.4 on 2023-01-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_booking_receiver_mobile_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partyaccounts",
            name="mobile_number",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="partyaccounts",
            name="password",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
