# Generated by Django 4.1.4 on 2023-01-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_partyaccounts_mobile_number_partyaccounts_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partyaccounts",
            name="opening_balance",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
