# Generated by Django 4.1.4 on 2023-01-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_partyaccounts_opening_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="refcourier",
            name="final_link",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name="refcourier",
            name="if_multiple",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="refcourier",
            name="milti_link",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
