# Generated by Django 4.1.4 on 2023-01-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_refcourier_final_link_refcourier_if_multiple_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="refcourier",
            name="multi_name",
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
