# Generated by Django 4.1.4 on 2023-02-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_rename_milti_link_refcourier_multi_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="refcourier",
            name="selenium",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
