# Generated by Django 4.1.4 on 2023-02-06 22:37

import api.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0019_refcourier_selenium"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAdditionalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(blank=True, max_length=256, null=True)),
                ("is_active", models.BooleanField(default=True, null=True)),
                ("purchase_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "licence_expire_date",
                    models.DateTimeField(default=api.models.new_date),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.destination",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "User Additional Details",},
        ),
    ]
