# Generated by Django 4.1.4 on 2023-03-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_bookingtype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingtype", options={"verbose_name_plural": "Booking type"},
        ),
    ]
