# Generated by Django 4.1.4 on 2023-03-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_bookingtype_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_type",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_types",
                to="api.bookingtype",
            ),
        ),
    ]
