# Generated by Django 4.1.4 on 2023-03-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_booking_booking_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="remarks",
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
