# Generated by Django 4.1.4 on 2023-03-18 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0025_booking_amount_booking_remarks_booking_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name", models.CharField(max_length=350, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "pincode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_code",
                        to="api.branchnetwork",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Area Master",},
        ),
        migrations.CreateModel(
            name="DeliveryBoyMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_boy_name", models.CharField(max_length=256, null=True)),
                ("mobile_number", models.CharField(max_length=15)),
                (
                    "alternate_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "area_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_names",
                        to="api.areamaster",
                    ),
                ),
                (
                    "pincode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_boy_pincode",
                        to="api.branchnetwork",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_detail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Delivery Boy Details",},
        ),
    ]
