# Generated by Django 4.1.4 on 2023-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_areamaster_deliveryboymaster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchnetwork",
            name="pincode",
            field=models.IntegerField(unique=True),
        ),
    ]
