# Generated by Django 4.1.4 on 2023-03-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_branchnetwork_pincode"),
    ]

    operations = [
        migrations.RemoveField(model_name="deliveryboymaster", name="pincode",),
    ]
