# Generated by Django 4.1.4 on 2023-05-21 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0028_remove_deliveryboymaster_pincode"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrsTransactionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docket_number", models.CharField(max_length=40, null=True)),
                ("origin", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "consignee_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("drs_number", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.parcelstatus",
                    ),
                ),
            ],
            options={"verbose_name_plural": "DRS Transaction History",},
        ),
        migrations.CreateModel(
            name="DrsNoGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drs_number", models.BigIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "DRS No. Generator",},
        ),
        migrations.CreateModel(
            name="DrsMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drs_no", models.CharField(max_length=25, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("Pending", "Pending"), ("Updated", "Updated")],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "area_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.areamaster",
                    ),
                ),
                (
                    "deliveryboy_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.deliveryboymaster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "DRS Master",},
        ),
    ]
