# Generated by Django 4.1.4 on 2023-05-24 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0029_drstransactionhistory_drsnogenerator_drsmaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="drstransactionhistory",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
