# Generated by Django 4.1.4 on 2023-05-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_drstransactionhistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="drstransactionhistory",
            name="reason",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
