# Generated by Django 4.1.4 on 2023-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_drstransactionhistory_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="drstransactionhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="drstransactionhistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
