# Generated by Django 4.1.4 on 2023-05-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_drstransactionhistory_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reasons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=560, null=True)),
            ],
            options={"verbose_name_plural": "Reasons",},
        ),
    ]
