# Generated by Django 4.1.4 on 2023-06-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_cnotegenerator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnotegenerator",
            name="from_range",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="cnotegenerator",
            name="to_range",
            field=models.BigIntegerField(null=True),
        ),
    ]
