# Generated by Django 4.1.4 on 2023-07-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_booking_actual_weight_booking_charged_weight_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="actual_weight",),
        migrations.AlterField(
            model_name="booking",
            name="pcs",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
