# Generated by Django 4.1.4 on 2023-07-08 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_remove_booking_actual_weight_alter_booking_pcs"),
    ]

    operations = [
        migrations.CreateModel(
            name="GstModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gst_name", models.CharField(max_length=50, null=True)),
                ("gst_rate", models.FloatField()),
            ],
            options={"verbose_name_plural": "Gst Details",},
        ),
        migrations.AddField(
            model_name="booking",
            name="gst_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="hsn_number",
            field=models.IntegerField(blank=True, default=996812, null=True),
        ),
        migrations.AddField(
            model_name="useradditionaldetails",
            name="gst_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="gst_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.gstmodel",
            ),
        ),
    ]
