# Generated by Django 4.1.4 on 2023-07-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_gstmodel_booking_gst_rate_booking_hsn_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="gst_name",),
        migrations.RemoveField(model_name="booking", name="hsn_number",),
        migrations.AddField(
            model_name="booking",
            name="c_i_gst",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="e_way_bill_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="gst_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="gst_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_mode",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="pincode",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.state",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="gst_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.gstmodel",
            ),
        ),
    ]
