# Generated by Django 4.1.4 on 2023-07-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_branchnetwork_contact_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_mode",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="mode_amount",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
