# Generated by Django 4.1.4 on 2023-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="status",
            field=models.CharField(blank=True, default="OPEN", max_length=50),
        ),
    ]
