# Generated by Django 4.1.4 on 2023-09-20 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0046_drspermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("message", models.CharField(blank=True, max_length=2000, null=True)),
                ("status", models.CharField(max_length=200, null=True)),
                ("by_user", models.CharField(blank=True, max_length=200, null=True)),
                ("doc_number", models.BigIntegerField()),
                (
                    "from_counter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="from_counter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_counter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="to_counter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Complaint Register",},
        ),
    ]
