# Generated by Django 4.1.4 on 2023-09-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_complaints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaints",
            name="message",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
