# Generated by Django 4.1.4 on 2023-10-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_userbooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbooking",
            name="ip_address",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="userbooking",
            name="pick_up",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="userbooking",
            name="s_pincode",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
