# Generated by Django 4.1.4 on 2023-12-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_userbooking_branch_aloted"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageMarquee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "message",
                    models.TextField(
                        blank=True, default="", max_length=2000, null=True
                    ),
                ),
            ],
            options={"verbose_name_plural": "Marquee message",},
        ),
    ]
