# Generated by Django 4.1.4 on 2023-12-09 17:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_messagemarquee"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagemarquee",
            name="message1",
            field=ckeditor.fields.RichTextField(
                blank=True, default="", max_length=2000, null=True
            ),
        ),
    ]
